### ISSUE TITLE
Reloading an ecaml module

### ISSUE THREAD

**Issue by abhi18av** [bcc32/ecaml-hello#2]
Hi @bcc32 , 

Thanks for your wonderful blog and the `bf-interpreter` - I found them really helpful!

I was wondering whether it's possible to dynamically reload a module, once it has been recompiled and reflect the changes within emacs?

**Comment by bcc32** [comment]
Hi @abhi18av, that's a great question.  I noticed you also posted to janestreet/ecaml#8.  You'll probably get better help there for general ecaml questions---this repository is just intended as an example.

As mentioned in the other thread, reloading is a little tricky because there is no clean way to "unload" a dynamic library, but generally this isn't too big of an issue, as long as you're willing to just let more and more OCaml runtimes pile up inside your Emacs instance :)

**Comment by abhi18av** [comment]
Yeah, I'm really looking forward not have `emacs` crashing once I reload the plugin hehe.

Thanks again!
